"""Model ecosystems: where models come from, as pluggable registries.

The mirror of :mod:`nnseg.sources` - sources answer "where inputs come from",
ecosystems answer "where models come from". A :class:`ModelEcosystem` names its
tasks, installs their weights, and materializes each task's :class:`TaskSpec`.
The rule learned from the stale total_mr class map applies throughout:
**the checkpoint is the spec** - a catalog holds only what the checkpoint
cannot know (where to download it, and how to compose multiple models).

Three ecosystems ship:

- ``ts`` - the TotalSegmentator catalog. Its tasks are *compositions* (unions,
  cascades, remaps) that exist only as application logic, so it carries a full
  task registry (guarded by the remap drift test).
- ``moose`` - MOOSE/moosez models. Bare, self-describing nnU-Net checkpoints
  on public release assets: the manifest holds name -> url + folder, and the
  spec is read from the installed checkpoint's own dataset.json.
- ``native`` - local model folders the operator registers explicitly.

An :class:`EcosystemCatalog` federates a registry of ecosystems behind the
same interface :class:`nnseg.tasks.TaskCatalog` exposes, so ``Segmenter`` and
the server run unchanged. Tasks whose weights are not yet installed are
listed but unmaterialized: ``info()`` says so without downloading, ``get()``
installs on demand (the same behavior TS weights ids always had).
"""
import json
import re
from pathlib import Path

from .errors import InputError, ModelNotFound
from .tasks import TaskCatalog, TaskSpec

MOOSE_MANIFEST = Path(__file__).parent / "data" / "moose_weights.json"


class ModelEcosystem:
    """One model repository: task names, weight installation, spec loading."""

    name: str = ""
    description: str = ""

    def tasks(self) -> list:
        raise NotImplementedError

    def materialized(self, task: str, root) -> bool:
        """Whether spec() can answer without installing anything."""
        raise NotImplementedError

    def ensure(self, task: str, root, progress=None) -> None:
        """Install the task's weights under ``root`` (idempotent)."""
        raise NotImplementedError

    def spec(self, task: str, root) -> TaskSpec:
        """The task's spec; requires materialized() unless the ecosystem
        carries composition data of its own."""
        raise NotImplementedError

    def info(self, task: str, root) -> dict:
        """Cheap metadata that never downloads: ecosystem, materialized, and
        whatever is knowable pre-install."""
        out = {"name": task, "ecosystem": self.name,
               "materialized": self.materialized(task, root)}
        if out["materialized"]:
            spec = self.spec(task, root)
            out["modality"] = spec.modality
            out["structures"] = sorted(spec.label_map.values())
        return out


class TSEcosystem(ModelEcosystem):
    """TotalSegmentator: composed tasks from the shipped registry JSON; weights
    by id from the release-asset manifest (license-gated models refuse with an
    actionable message). Always materialized - the composition data carries
    the label maps, and the remap drift test keeps them honest."""

    name = "ts"
    description = "TotalSegmentator task catalog"

    def __init__(self):
        self._catalog = TaskCatalog("totalsegmentator")

    def tasks(self) -> list:
        return self._catalog.names()

    def materialized(self, task: str, root) -> bool:
        return True

    def ensure(self, task: str, root, progress=None) -> None:
        from .weights_fetch import ensure_task_weights
        ensure_task_weights(task, root, catalog=self._catalog, progress=progress)

    def spec(self, task: str, root) -> TaskSpec:
        return self._catalog.get(task)


class MooseEcosystem(ModelEcosystem):
    """MOOSE (moosez): bare nnU-Net checkpoints from public GitHub release
    assets, installed under ``<root>/moose/<Dataset folder>`` and read through
    ``TaskSpec.from_model_folder`` - labels come from each checkpoint's own
    dataset.json, so there is no class map here to drift. The manifest
    (``data/moose_weights.json``, regenerated by tools/gen_moose_manifest.py
    from the moosez registry) holds only name -> url + folder + release tag."""

    name = "moose"
    description = "MOOSE (moosez) model zoo"

    def __init__(self, manifest=None):
        raw = json.loads(Path(manifest or MOOSE_MANIFEST).read_text())
        self._entries = raw["tasks"] if isinstance(raw, dict) else raw

    def tasks(self) -> list:
        return sorted(self._entries)

    def _folder(self, task: str, root) -> Path:
        return Path(root).expanduser() / "moose" / self._entries[task]["folder"]

    def materialized(self, task: str, root) -> bool:
        if task not in self._entries:
            return False
        d = self._folder(task, root)
        return d.is_dir() and any(d.rglob("dataset.json"))

    def ensure(self, task: str, root, progress=None) -> None:
        if self.materialized(task, root):
            return
        entry = self._entries[task]
        dest_parent = Path(root).expanduser() / "moose"
        dest_parent.mkdir(parents=True, exist_ok=True)
        _download_and_extract_zip(entry["url"], dest_parent, progress=progress)
        folder = self._folder(task, root)
        if not folder.is_dir():
            raise ModelNotFound(
                f"moose asset for {task!r} unpacked without the expected folder "
                f"{entry['folder']!r} - the manifest may be stale; regenerate it "
                "with tools/gen_moose_manifest.py")
        from .weights_fetch import _write_sidecar
        _write_sidecar(folder, task, entry.get("tag", "unknown"),
                       {"url": entry["url"]}, None)

    def spec(self, task: str, root) -> TaskSpec:
        if not self.materialized(task, root):
            raise ModelNotFound(
                f"moose task {task!r} is not installed under {root}; prepare it "
                "first (weights install on demand when the task runs)")
        return TaskSpec.from_model_folder(self._folder(task, root), name=task)

    def info(self, task: str, root) -> dict:
        out = super().info(task, root)
        m = re.match(r"(clin|preclin)_(ct|mr|pt|fdg_pt|pt_fdg)_", task)
        if "modality" not in out and m:
            out["modality"] = m.group(2).upper().replace("FDG_PT", "PT").replace("PT_FDG", "PT")
        out["tag"] = self._entries.get(task, {}).get("tag")
        return out


class NativeEcosystem(ModelEcosystem):
    """Local model folders registered by the operator: always materialized,
    nothing to install. The folder is read through from_model_folder, so the
    checkpoint's dataset.json is the spec here too."""

    name = "native"
    description = "operator-registered local nnU-Net model folders"

    def __init__(self, models: dict | None = None):
        self._models = {str(k): Path(v) for k, v in (models or {}).items()}

    def tasks(self) -> list:
        return sorted(self._models)

    def materialized(self, task: str, root) -> bool:
        return task in self._models and self._models[task].is_dir()

    def ensure(self, task: str, root, progress=None) -> None:
        if not self.materialized(task, root):
            raise ModelNotFound(f"native task {task!r}: folder "
                                f"{self._models.get(task)} does not exist")

    def spec(self, task: str, root) -> TaskSpec:
        self.ensure(task, root)
        return TaskSpec.from_model_folder(self._models[task], name=task)


def _download_and_extract_zip(url: str, dest_parent: Path, *, progress=None) -> None:
    """Fetch a release zip and unpack it under ``dest_parent``, refusing any
    member whose path would escape (zip-slip)."""
    import tempfile
    import urllib.request
    import zipfile
    if progress:
        progress(f"downloading {url.rsplit('/', 1)[-1]}")
    with tempfile.NamedTemporaryFile(suffix=".zip", dir=dest_parent, delete=False) as tmp:
        tmp_path = Path(tmp.name)
        try:
            with urllib.request.urlopen(url, timeout=1800) as r:
                while chunk := r.read(1 << 20):
                    tmp.write(chunk)
        except Exception as e:
            tmp_path.unlink(missing_ok=True)
            raise InputError(f"weights download failed: {e}") from e
    try:
        with zipfile.ZipFile(tmp_path) as z:
            base = dest_parent.resolve()
            for m in z.infolist():
                target = (dest_parent / m.filename).resolve()
                if not target.is_relative_to(base):
                    raise InputError(f"zip member escapes destination: {m.filename!r}")
            z.extractall(dest_parent)
    finally:
        tmp_path.unlink(missing_ok=True)


def registry(ecosystems=None) -> dict:
    """Normalize a list of ecosystems into ``{name: ecosystem}``, rejecting
    duplicate names and cross-ecosystem task-name collisions."""
    out, seen_tasks = {}, {}
    for e in (default_ecosystems() if ecosystems is None else list(ecosystems)):
        if not e.name or e.name in out:
            raise ValueError(f"bad or duplicate ecosystem name {e.name!r}")
        for t in e.tasks():
            if t in seen_tasks:
                raise ValueError(f"task name {t!r} exists in both "
                                 f"{seen_tasks[t]!r} and {e.name!r}")
            seen_tasks[t] = e.name
        out[e.name] = e
    return out


def default_ecosystems() -> list:
    return [TSEcosystem(), MooseEcosystem()]


class EcosystemCatalog:
    """A TaskCatalog-compatible federation over an ecosystem registry.

    ``get()`` materializes on demand (installing weights if the task needs
    that - the same on-first-use behavior TS weights ids always had);
    ``info()`` never downloads. A TaskSpec or a model-folder path passes
    through ``get`` untouched, as with TaskCatalog."""

    def __init__(self, ecosystems=None, *, root=None):
        self.registry = registry(ecosystems)
        self.root = root
        self._by_task = {t: e for e in self.registry.values() for t in e.tasks()}

    def names(self) -> list:
        return sorted(self._by_task)

    def __contains__(self, name) -> bool:
        return name in self._by_task

    def __len__(self) -> int:
        return len(self._by_task)

    def ecosystem_of(self, name: str):
        return self._by_task.get(name)

    def get(self, name) -> TaskSpec:
        if isinstance(name, TaskSpec):
            return name
        eco = self._by_task.get(str(name))
        if eco is None:
            raise LookupError(f"unknown task {name!r}; {len(self._by_task)} known, "
                              f"e.g. {self.names()[:6]}")
        if not eco.materialized(name, self.root):
            eco.ensure(name, self.root)
        return eco.spec(name, self.root)

    __getitem__ = get

    def info(self, name: str) -> dict:
        eco = self._by_task.get(name)
        if eco is None:
            raise LookupError(f"unknown task {name!r}")
        return eco.info(name, self.root)

    def prepare(self, name: str, progress=None) -> dict:
        """Install the task's weights now and return its full info."""
        eco = self._by_task.get(name)
        if eco is None:
            raise LookupError(f"unknown task {name!r}")
        eco.ensure(name, self.root, progress=progress)
        return eco.info(name, self.root)
